### ISSUE TITLE
Refactor Registration and Login component

### ISSUE THREAD

**Issue by dejan-xd** [nole23/UKS#10]
Optimizovati kod registracije i logovanja korisnika. Potrebno je izbaciti nepotreban kod i koristiti odgovarajuce biblioteke za hesovanje sifre u bazi kao i logovanje.

**Comment by nole23** [comment]
Refaktorizacija je zavrsena, trebalo bi zatvoriti ovaj issue.

**Comment by dejan-xd** [comment]
Važi, zatvaram issue.
