### ISSUE TITLE
Show all repository.

### ISSUE THREAD

**Issue by nole23** [nole23/UKS#13]
Kreirati tabelu sa prikazom svih kreiranih repoa koje smo kreirali i one na kojima imamo privilegije da ih mjenjamo.
Treba napraviti razliku izmedju ovih repositorijuma (u vidu boje ili nekog simbola. Ovo osmisliti sam)

**Comment by dejan-xd** [comment]
Svi projekti jednog korisnika su prikazani.
Kreiram novi issue za postavljanje markera za projekte na koima imam privilegije
