### ISSUE TITLE
Show one issue

### ISSUE THREAD

**Issue by nole23** [nole23/UKS#18]
Obezbediti prikaz jednoj issues.

Ovde je potrebno obezbediti:
* Editovanje issue-a
* Brisanje issue-a
* Komentarisanje issue-a
* Preuzimanje issues-a na sebe
* Progres issue-a
* Povezati issue sa kodoma

**Comment by jovan92** [comment]
Preuzimam task.

**Comment by jovan92** [comment]
Odlučeno je da se tačka **_Povezati issue sa kodom_** ne radi u HF1
