### ISSUE TITLE
Create class models

### ISSUE THREAD

**Issue by nole23** [nole23/UKS#2]
Kreirati model klasa koji se mapira na bazu.
Modeli koji su trenutno potrebni uraditi:
1. Users
2. Issues
3. Roles
4. MyProjects
5. ProjectType
ListFrieds
Graph
ProjectVisitors
...

Treba osmisliti način povezivanja kao i klase koje se odnose na git i issues

**Comment by jovan92** [comment]
Napravljeni su modeli za bazu. Proverite da li je ok, pa javite da mogu zatvarati issue.

**Comment by jovan92** [comment]
@nole23 @Blyatiful-git

**Comment by nole23** [comment]
Mozes zatvarati.

**Comment by jovan92** [comment]
Zatvaram issue2
