### ISSUE TITLE
Edit file not correct

### ISSUE THREAD

**Issue by nole23** [nole23/UKS#52]
Kada kliknem na olovku kako bi izmjenio neki fajl. Fajl se otovri ja unesem poruku medjutim ako kliknem cacle 
i zelim da odustanem od toga, nova poruka se prikaze. Trebalo bi da vrati staru poruku.

Olovka na README.md na pocetnoj stranici ne radi nista. Ovo treba srediti da ovori edit ili ukloniti ovu opciju.

Kada se otvori neki fajl djeluje da ime fajla se nalazi u tijelu fajla, treba dizajnerski razdvojiti zaglavlje od tijela.

Omoguciti opciju za brisanje fajla, ovo ne posotji treba uvesti.

**Comment by jovan92** [comment]
Dugme za edit README.md fajla je uklonjena na početno stranici.
Dugme Cancel/Save fajlova je prepravljeno tako da sad radi očekivano.
Ime i telo fajla su razdvojeni linijom.
Dodato je dugme Delete u zaglavlju fajla, i implemetnirano je brisanje istog.
